In [3]:
import numpy as np

# 创建数组

In [4]:
print(np.eye(5))
print(np.array([1, 2, 3, 5]))
print(np.zeros(5))
print(np.ones(5))
print(np.arange(1, 10, 2))
print(np.linspace(18, 20, 12))
print(np.eye(5).shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1 2 3 5]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 3 5 7 9]
[18.         18.18181818 18.36363636 18.54545455 18.72727273 18.90909091
 19.09090909 19.27272727 19.45454545 19.63636364 19.81818182 20.        ]
(5, 5)


# 数组属性

In [7]:
a = np.random.rand(2, 3)
print(a.shape, a.dtype, a.size, a.ndim)

(2, 3) float64 6 2


# 数学操作

In [11]:
print(a)
print(np.sum(a))
print(np.std(a))
print(np.max(a))
print(np.mean(a))


[[0.19017767 0.16782715 0.92855957]
 [0.43965076 0.7602876  0.7110609 ]]
3.1975636527432147
0.2885091335451873
0.9285595665556694
0.5329272754572024


# 随机数生成

In [13]:
# 指定维度，样本位于[0, 1)的随机样本 
print(np.random.rand(2, 3))
# 指定维度，样本为正态分布随机值的数组
print(np.random.randn(2, 3))


[[0.04219618 0.9572159  0.63788287]
 [0.80968587 0.37063256 0.66921566]]
[[-0.94223072  0.30441249 -2.6774548 ]
 [ 0.89406486  1.36746069 -0.80088955]]
